### PR TITLE
Get UUID prefix from env variable POD_NAME, not os.Hostname()

### PR DESCRIPTION
**Pull request by nkinkade**
We discovered this issue: https://github.com/m-lab/k8s-support/issues/687

This PR causes the "create-uuid-prefix-file" utility to get the UUID prefix from the environment variable `POD_NAME` instead of from `os.Hostname()`, since the hostname inside of a container may be variable.

This PR depends upon this one: https://github.com/m-lab/k8s-support/pull/688

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid/9)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`prefix/prefix.go` line 49 at r1](https://reviewable.io/reviews/m-lab/uuid/9#-N3QJzYu83knUmhAPiMB:-N3QJzYu83knUmhAPiMC:bgjotnf) ([raw file](https://github.com/m-lab/uuid/blob/922a54fd39d2bdbca9f25912efc0e638dc94fbe7/prefix/prefix.go#L49)):*
> ```Go
> // string is the empty string.
> func generate(extras []string) (string, error) {
> 	podName, ok := osLookupEnv("POD_NAME")
> ```

Every machine has a HOSTNAME by default. Not every environment has a POD_NAME unless its in a Kubernetes environment. If we want this functionality, I recommend preferring `POD_NAME` and falling back to hostname if not found.

Also, is HOSTNAME== POD_NAME when `hostNetwork:true`? for example, does this conditional already apply for the host experiment sidecar data?

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`prefix/prefix.go` line 49 at r1](https://reviewable.io/reviews/m-lab/uuid/9#-N3QJzYu83knUmhAPiMB:-N3QUDWE3fKC7TcC-jhb:bvtgpau) ([raw file](https://github.com/m-lab/uuid/blob/922a54fd39d2bdbca9f25912efc0e638dc94fbe7/prefix/prefix.go#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Every machine has a HOSTNAME by default. Not every environment has a POD_NAME unless its in a Kubernetes environment. If we want this functionality, I recommend preferring `POD_NAME` and falling back to hostname if not found.

Also, is HOSTNAME== POD_NAME when `hostNetwork:true`? for example, does this conditional already apply for the host experiment sidecar data?
</blockquote></details>

I phrased the question poorly.

Are we observing the machine name in HOSTNAME because `hostNetwork: true`? If so, then perhaps this was WAI? If we would like to make the UUID naming consistently use the POD NAME when available, then I would recommend preserving the option of running outside of a Kubernetes environment.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`prefix/prefix.go` line 49 at r1](https://reviewable.io/reviews/m-lab/uuid/9#-N3QJzYu83knUmhAPiMB:-N3VafT-81Zc4ynBmrLe:bvxze0p) ([raw file](https://github.com/m-lab/uuid/blob/922a54fd39d2bdbca9f25912efc0e638dc94fbe7/prefix/prefix.go#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I phrased the question poorly.

Are we observing the machine name in HOSTNAME because `hostNetwork: true`? If so, then perhaps this was WAI? If we would like to make the UUID naming consistently use the POD NAME when available, then I would recommend preserving the option of running outside of a Kubernetes environment.
</blockquote></details>

Ah, that is a great observation, and I just verified that your hunch is true. `hostname` in a pod that is running with `hostNetwork: true` will indeed be the same as what is returned when running a normal shell on the machine.  And indeed, the annotation files for the "host" experiment are named incorrectly, too. For example:

```
/cache/data/host/annotation/2022/06/01/mlab1-den04.mlab-oti.measurement-lab.org_1652876502_000000000009F312.json
```

I have update my changes to prefer the value of `POD_NAME`, when it exists, falling back to the value of `os.Hostname()`.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: I have implemented your suggestion, and it should make the utility more robust. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/9#-:-N3VkwcQ2-gPj7Vi487I:b-qzayu3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`prefix/prefix.go` line 55 at r2](https://reviewable.io/reviews/m-lab/uuid/9#-N3VoIbO0qQBabqevym0:-N3VoIbP1EmookhD5kE1:b-qplt2w) ([raw file](https://github.com/m-lab/uuid/blob/885055a98fe1e6125b3fbed0912197b2b98f5b7f/prefix/prefix.go#L55)):*
> ```Go
> 	prefixValue, ok := osLookupEnv("POD_NAME")
> 	if !ok || prefixValue == "" {
> 		prefixValue, err := osHostname()
> ```

This assignment uses `:=` which is locally scoped. Outside the if block, you'll get the value from the outer definition of `prefixValue`.. Please confirm with a unit test.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`prefix/prefix.go` line 55 at r2](https://reviewable.io/reviews/m-lab/uuid/9#-N3VoIbO0qQBabqevym0:-N3W1avh0LOOs_1XtiXG:b-fyguxa) ([raw file](https://github.com/m-lab/uuid/blob/885055a98fe1e6125b3fbed0912197b2b98f5b7f/prefix/prefix.go#L55)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This assignment uses `:=` which is locally scoped. Outside the if block, you'll get the value from the outer definition of `prefixValue`.. Please confirm with a unit test.
</blockquote></details>

@stephen-soltesz: thank you for catching that. Fixed, and I've updated the unit tests to explicitly test for this, I believe. PTAL?

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`prefix/prefix.go` line 54 at r3](https://reviewable.io/reviews/m-lab/uuid/9#-N3WBPlSDIRWwKNZDOBv:-N3WBPlSDIRWwKNZDOBw:b-u0jcxl) ([raw file](https://github.com/m-lab/uuid/blob/f0ab7bbf23bdf8de837ea2f43cf38610366ddf74/prefix/prefix.go#L54)):*
> ```Go
> 	// as the prefix for the UUID, else fall back on using the value of
> 	// os.Hostname().
> 	prefixValue, ok := osLookupEnv("POD_NAME")
> ```

Thank you for the updates.

Unfortunately, I cannot verify that the unit tests are covering the "pod name failed, hostname succeeded" case. This is a short coming of "100% coverage", I think.

Please create a helper function for "getPrefix()` or similar, so the logic is not a double nested condition. This is easy to verify as correct-by-inspection, and the unit test coverage guarantees that each branch is visited.

```
func getPrefix() string {
    prefixValue, ok := osLookupEnv("POD_NAME")
    if ok {
        return prefixValue
    }
    prefixValue, err = osHostname()
    if err == nil {
        return prefixValue
    }
    return "BADHOSTNAME", err
}
```



_Code quote:_
```Go
	prefixValue, ok := osLookupEnv("POD_NAME")
	if !ok || prefixValue == "" {
		prefixValue, err = osHostname()
		if err != nil {
			return "BADHOSTNAME", err
		}
	}
```

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`prefix/prefix.go` line 54 at r3](https://reviewable.io/reviews/m-lab/uuid/9#-N3WBPlSDIRWwKNZDOBv:-N3WOM3y2vhzcGz14b9I:b4dy9ru) ([raw file](https://github.com/m-lab/uuid/blob/f0ab7bbf23bdf8de837ea2f43cf38610366ddf74/prefix/prefix.go#L54)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you for the updates.

Unfortunately, I cannot verify that the unit tests are covering the "pod name failed, hostname succeeded" case. This is a short coming of "100% coverage", I think.

Please create a helper function for "getPrefix()` or similar, so the logic is not a double nested condition. This is easy to verify as correct-by-inspection, and the unit test coverage guarantees that each branch is visited.

```
func getPrefix() string {
    prefixValue, ok := osLookupEnv("POD_NAME")
    if ok {
        return prefixValue
    }
    prefixValue, err = osHostname()
    if err == nil {
        return prefixValue
    }
    return "BADHOSTNAME", err
}
```
</blockquote></details>

@stephen-soltesz: thanks for the feedback. I have implemented the `getPrefix()` function, with a few minor changes from your suggestion.  I have also added a new unit test for the specific "pod name failed, hostname succeeded" case you mentioned. PTAL?

**Review by stephen-soltesz — APPROVED** [review]
Thank you!

:lgtm:

> Reviewed 5 of 7 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/9#-:-N3WPb5r8SvEbongzGu1:b3oh6o9)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
