### PR TITLE
Fix UUID bug

### PR DESCRIPTION
**Pull request by pboothe**
Adds the design doc, and fixes the UUID timestamp generation.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid/1)

### CODE REVIEW

**Comment by pboothe** [comment]
A task in story #2

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/1#-:-LaM8UjU8WiTd2bIz9Of:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pboothe and @stephen-soltesz)

___
*[DESIGN.md, line 11 at r2](https://reviewable.io/reviews/m-lab/uuid/1#-LaLqa132YhqQvWobwDO:-LaLqa143myCWBU1ttqJ:bgiqdl9) ([raw file](https://github.com/m-lab/uuid/blob/2e0105c2f21d19c594146055398f34224bd5d647/DESIGN.md#L11)):*
> ```
> is just awful
> ```

I agree. But, please rephrase in the intro. This may not be the tone we want to start with for our solution. The Background goes into more detail about why there is a problem.
___
*[DESIGN.md, line 42 at r2](https://reviewable.io/reviews/m-lab/uuid/1#-LaM6x9ICWsy8-jeq09Q:-LaM6x9ICWsy8-jeq09R:b-asf0is) ([raw file](https://github.com/m-lab/uuid/blob/2e0105c2f21d19c594146055398f34224bd5d647/DESIGN.md#L42)):*
> ```Markdown
> - socket TCP cookie (also in hex, a fixed-digit hexadecimal encoding of a 64 bit number)
> 
> all joined with underscores. e.g.: `pboothe2.nyc.corp.google.com_1548788619_00000000000084FF`
> ```

Technically, this fqdn should not be public. That's not me being picky -- googlers were chastised for this since my time at Google.
___
*[DESIGN.md, line 81 at r2](https://reviewable.io/reviews/m-lab/uuid/1#-LaM88dU5LEQ5K-7YLMU:-LaM88dU5LEQ5K-7YLMV:b-ynopuv) ([raw file](https://github.com/m-lab/uuid/blob/2e0105c2f21d19c594146055398f34224bd5d647/DESIGN.md#L81)):*
> ```
> Linux-imposed foolishness.
> ```

"limitation in Linux".
___
*[README.md, line 14 at r1](https://reviewable.io/reviews/m-lab/uuid/1#-LaLe9RTDAlYMj9ysNYV:-LaLe9RTDAlYMj9ysNYW:bd2sdnu) ([raw file](https://github.com/m-lab/uuid/blob/fc67196f9da75676a5e960406d83a34c55f378d0/README.md#L14)):*
> ```Markdown
> 
> The design of the UUIDs and this system for creating them can be found in
> `[./DESIGN.md]`.  
> ```

Looks like extra EOL spaces and no trailing new line.

These vscode settings can help:
```
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true
```

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/1)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pboothe and @stephen-soltesz)

___
*[DESIGN.md, line 42 at r2](https://reviewable.io/reviews/m-lab/uuid/1#-LaM6x9ICWsy8-jeq09Q:-LaM8wFT1M_w9t68iNnG:bz1smkk) ([raw file](https://github.com/m-lab/uuid/blob/2e0105c2f21d19c594146055398f34224bd5d647/DESIGN.md#L42)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Technically, this fqdn should not be public. That's not me being picky -- googlers were chastised for this since my time at Google.
</blockquote></details>

Hmm - I wonder if we need to expunge it from the github history?

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/1)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[DESIGN.md, line 11 at r2](https://reviewable.io/reviews/m-lab/uuid/1#-LaLqa132YhqQvWobwDO:-LaM9xKsBbruDlKPU-KB:b-896fix) ([raw file](https://github.com/m-lab/uuid/blob/2e0105c2f21d19c594146055398f34224bd5d647/DESIGN.md#L11)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> ```
> is just awful
> ```

I agree. But, please rephrase in the intro. This may not be the tone we want to start with for our solution. The Background goes into more detail about why there is a problem.
</blockquote></details>

Done.
___
*[DESIGN.md, line 42 at r2](https://reviewable.io/reviews/m-lab/uuid/1#-LaM6x9ICWsy8-jeq09Q:-LaM9z3i4KYusPl7AAYu:b1ezoqt) ([raw file](https://github.com/m-lab/uuid/blob/2e0105c2f21d19c594146055398f34224bd5d647/DESIGN.md#L42)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Hmm - I wonder if we need to expunge it from the github history?
</blockquote></details>

I will "squash and merge" to make sure it does not appear in the revision history for the master branch.
___
*[DESIGN.md, line 81 at r2](https://reviewable.io/reviews/m-lab/uuid/1#-LaM88dU5LEQ5K-7YLMU:-LaM9yma2lNGUqhtMgW1:b-896fix) ([raw file](https://github.com/m-lab/uuid/blob/2e0105c2f21d19c594146055398f34224bd5d647/DESIGN.md#L81)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> ```
> Linux-imposed foolishness.
> ```

"limitation in Linux".
</blockquote></details>

Done.
___
*[README.md, line 14 at r1](https://reviewable.io/reviews/m-lab/uuid/1#-LaLe9RTDAlYMj9ysNYV:-LaMACDs5E_RxgwizG5U:b-896fix) ([raw file](https://github.com/m-lab/uuid/blob/fc67196f9da75676a5e960406d83a34c55f378d0/README.md#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Looks like extra EOL spaces and no trailing new line.

These vscode settings can help:
```
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true
```
</blockquote></details>

Done.

**Pull request merged**
