### PR TITLE
Upgrade repo to Go 1.18

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/uuid/11)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/11)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`Dockerfile` line 8 at r1](https://reviewable.io/reviews/m-lab/uuid/11#-N9hVRRN1Yz7YCF8jqJk:-N9hVRRN1Yz7YCF8jqJl:b-yca29p) ([raw file](https://github.com/m-lab/uuid/blob/577d4c8892867e1b71fd08d448585a384eee89df/Dockerfile#L8)):*
> ```Dockerfile
> COPY --from=uuid-creator-build /go/bin/create-uuid-prefix-file /
> WORKDIR /
> # Make sure /uuid-annotator can run (has no missing external dependencies).
> ```

Do you mean "Make sure /create-uuid-prefix-file ..."?

**Comment by SaiedKazemi** [comment]
*[`Dockerfile` line 8 at r1](https://reviewable.io/reviews/m-lab/uuid/11#-N9hVRRN1Yz7YCF8jqJk:-N9hXqxQ2j4mT06fH6lX:bgofkhy) ([raw file](https://github.com/m-lab/uuid/blob/577d4c8892867e1b71fd08d448585a384eee89df/Dockerfile#L8)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Do you mean "Make sure /create-uuid-prefix-file ..."?
</blockquote></details>

Copy and paste got me :(

**Comment by SaiedKazemi** [comment]
PTAL

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/uuid/11#-:-N9hZBJn5i9pstcn_a6a:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

**Pull request merged**
